#!/usr/bin/env node
// Responsibility: roll `results/*/*.json` (harness/run-target.mjs's output)
// up into one target x track x pass/fail table, written into README.md
// between the RESULTS markers below. Every result file on disk gets a row
// — including a failing one — this is a status table, not a highlight
// reel: `run-target.mjs`'s own header/report notes when a run's exit code
// or scenario count doesn't clear the target's bar, and this table is
// where that stays visible after the fact.
//
//   node harness/render-readme.mjs
//
// npm track can accumulate more than one persistent `<semver>.json` over
// time (harness/run-target.mjs never overwrites one once written); every
// one found gets its own row, newest semver first. `main.json` always
// overwrites in place, so it is always exactly one row per target.

import { readFileSync, readdirSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const REPO_ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const RESULTS_DIR = path.join(REPO_ROOT, "results");
const README_PATH = path.join(REPO_ROOT, "README.md");

const START_MARKER = "<!-- RESULTS:START (generated by harness/render-readme.mjs — do not hand-edit) -->";
const END_MARKER = "<!-- RESULTS:END -->";

function semverCompareDesc(a, b) {
  const pa = a.split(".").map(Number);
  const pb = b.split(".").map(Number);
  for (let i = 0; i < 3; i++) {
    if (pa[i] !== pb[i]) return pb[i] - pa[i];
  }
  return 0;
}

function loadResultFiles() {
  if (!existsDir(RESULTS_DIR)) return [];
  const rows = [];
  for (const targetId of readdirSync(RESULTS_DIR, { withFileTypes: true })
    .filter((e) => e.isDirectory())
    .map((e) => e.name)
    .sort()) {
    const dir = path.join(RESULTS_DIR, targetId);
    const files = readdirSync(dir).filter((f) => f.endsWith(".json"));
    const npmFiles = files.filter((f) => f !== "main.json").sort((a, b) => semverCompareDesc(a, b));
    const mainFiles = files.filter((f) => f === "main.json");
    for (const file of [...npmFiles, ...mainFiles]) {
      const data = JSON.parse(readFileSync(path.join(dir, file), "utf8"));
      rows.push({ targetId, file, data });
    }
  }
  return rows;
}

function existsDir(dir) {
  try {
    return readdirSync(dir) !== undefined;
  } catch {
    return false;
  }
}

function statusEmoji(pass) {
  return pass ? "PASS" : "FAIL";
}

function renderTable(rows) {
  if (rows.length === 0) {
    return "_No results yet — run `node harness/run-target.mjs <target> --track=npm|main` first._\n";
  }
  const header = [
    "| target | track | version / commit | run (exit, scenarios) | check (exit) | tend (exit) | overall |",
    "|---|---|---|---|---|---|---|",
  ];
  const lines = rows.map(({ targetId, data }) => {
    const versionCol = data.track === "npm" ? data.nukadokoVersion : (data.commitSha ?? "").slice(0, 12);
    const runCol = `${data.run.exitCode} (${data.run.scenarioCount}/${data.expectedScenarioCount})`;
    return `| ${targetId} | ${data.track} | ${versionCol} | ${runCol} | ${data.check.exitCode} | ${data.tend.exitCode} | ${statusEmoji(data.pass)} |`;
  });
  return [...header, ...lines].join("\n") + "\n";
}

function main() {
  const rows = loadResultFiles();
  const table = renderTable(rows);
  const block = `${START_MARKER}\n\n${table}\n${END_MARKER}`;

  let readme = "";
  try {
    readme = readFileSync(README_PATH, "utf8");
  } catch {
    readme = `# nukadoko-compat-lab\n\n${START_MARKER}\n\n${END_MARKER}\n`;
  }

  const startIndex = readme.indexOf(START_MARKER);
  const endIndex = readme.indexOf(END_MARKER);
  let next;
  if (startIndex !== -1 && endIndex !== -1) {
    next = readme.slice(0, startIndex) + block + readme.slice(endIndex + END_MARKER.length);
  } else {
    next = `${readme.trimEnd()}\n\n${block}\n`;
  }

  writeFileSync(README_PATH, next);
  console.log(`wrote ${rows.length} row(s) to ${README_PATH}`);
}

main();
